### ISSUE TITLE
Missing some code path in Blueprint (version 4.21 Marketplace)

### ISSUE THREAD

**Issue by simonjames247** [stomt/stomt-unreal-plugin#10]
In the "StomtWidgetBP", "Close" function miss the path after decide whether to switch wish or not, it only handles one path. This cause the "OnClose" delegate never fired in case of "I wish".

![https://i.imgur.com/g8rVygU.jpg](https://i.imgur.com/g8rVygU.jpg)

**Comment by maxklenk** [comment]
Thanks for pointing this out. We will reproduce and fix the problem.

**Comment by maxklenk** [comment]
Good catch, there was no reason why this path was missing. I added it as suggested by you. The fix will be included in the next release.
