### ISSUE TITLE
[Unreal Engine 4.17.3] When giving feedback, a click is required to focus the widget.

### ISSUE THREAD

**Issue by NarodGaming** [stomt/stomt-unreal-plugin#9]
When the widget is opened (using my hotkey of "Y" at the moment), the mouse isn't properly focused to the feedback windows, and instead controls the camera until I click on the widget to focus it. The same applies when coming off the widget - except in reverse.

**Comment by philippzentner** [comment]
@maxklenk @daniel-schukies have you seen this?

**Comment by maxklenk** [comment]
Yes, it is fixed in the new version 2.2.4
